site_name: MINT
site_url: https://github.com/sorenwacker/ms-mint
site_author: Soren Wacker 
nav:
  - Home: 'index.md'
  - Background: 'background.md'
  - Installation: 'install.md'
  - GUI: 'gui.md'
  - Peaklists: 'peaklists.md'
  #- Peak detection: 'peak-detection.md'
  #- Python: 'python.md'
  - Jupyter: 'jupyter.md'
  - Developer Notes: 'developer-notes.md'
  - Gallery: gallery.
extra:
  analytics:
    provider: google
    property: G-KZQBC4NMD2