site_name: MINT Documentation
site_url: https://github.com/soerendip/ms-mint
site_author: Soren Wacker
nav:
  - Home: 'index.md'
  - Mint GUI: 'gui.md'
  - Python API: 'python.md'
  - Jupyter Integration: 'jupyter.md'