name: Create Documentation
on:
  push:
    branches:
      - develop
      - docs/mkdocs
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Install your package to ensure autodoc works
      - name: Install ms_mint package and dependencies
        run: 
          python -m pip install --upgrade pip
          pip install -e ".[docs]"

      # Build the MkDocs documentation
      - name: Build Documentation
        run: |
          mkdocs build --clean

      # Deploy the built documentation to the gh-pages branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site  # MkDocs builds to the 'site' directory by default