name: Create Documentation
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: 3.12  # Adjust if needed
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install myst-parser sphinx-rtd-theme  # Install myst_parser and sphinx_rtd_theme
        pip install -r requirements.txt  # If you have additional requirements
    - name: Build Documentation
      run: |
        sphinx-build -b html docs/ build/ -W -v
    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
